knp_paginator:
  page_range: 5 # Nombre de pages visibles autour de la page courante
  default_options:
    page_name: page # Nom du paramètre de la page dans l'URL
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true # Évite les doublons
  template:
    pagination: "@KnpPaginator/Pagination/tailwindcss_pagination.html.twig" # Modèle pour Bootstrap 5
    sortable: "@KnpPaginator/Pagination/sortable_link.html.twig"
