vich_uploader:
  db_driver: orm
  mappings:
    article_images:
      uri_prefix: /uploads/images/articles
      upload_destination: "%kernel.project_dir%/public/uploads/images/articles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
